"use strict";
exports.__esModule = true;
var Car_1 = require("./Car");
var Colors_1 = require("./Colors");
var Directions_1 = require("./Directions");
var Doors_1 = require("./Doors");
var gol = new Car_1["default"]("Volksvagem", Colors_1["default"].SILVER, 4);
gol.openTheDoor(Doors_1["default"].DRIVER);
gol.closeTheDoor(Doors_1["default"].DRIVER);
gol.turnOn();
gol.speedUp();
gol.speedDown();
gol.turn(Directions_1["default"].LEFT);
gol.speedUp();
gol.speedDown();
gol.turn(Directions_1["default"].RIGHT);
gol.speedUp();
gol.speedDown();
gol.turn(Directions_1["default"].RIGHT);
gol.speedDown();
gol.stop();
gol.openTheDoor(Doors_1["default"].BEHIND_RIDE);
gol.closeTheDoor(Doors_1["default"].BEHIND_RIDE);
gol.speedUp();
gol.speedDown();
gol.turn(Directions_1["default"].RIGHT);
gol.speedUp();
gol.speedDown();
gol.turn(Directions_1["default"].LEFT);
gol.speedUp();
gol.speedDown();
gol.turn(Directions_1["default"].RIGHT);
gol.speedDown();
gol.stop();
gol.openTheDoor(Doors_1["default"].BEHIND_RIDE);
gol.closeTheDoor(Doors_1["default"].BEHIND_RIDE);
gol.speedUp();
